-- =============================================================================
--  BROWSER HABIT TRACKER — Database Setup
--  Run inside WSL:  psql -U postgres -f setup.sql
-- =============================================================================

-- 1. Create database (run as postgres superuser)
CREATE DATABASE browser_habit_tracker;

\c browser_habit_tracker

-- 2. Enable UUID extension (used for gen_random_uuid if needed)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 3. Core table — one row per active-focus period on a tab
--    IDs are UUIDs generated by the Chrome extension (crypto.randomUUID())
CREATE TABLE IF NOT EXISTS activity_sessions (
    id                  UUID            PRIMARY KEY,
    start_time          TIMESTAMPTZ     NOT NULL,
    end_time            TIMESTAMPTZ,
    duration_seconds    INTEGER,
    url                 TEXT            NOT NULL,
    domain              VARCHAR(255),
    title               TEXT,
    tab_id              INTEGER,
    window_id           INTEGER,
    browser             VARCHAR(50)     DEFAULT 'Chrome',
    created_at          TIMESTAMPTZ     DEFAULT NOW()
);

-- 4. Indexes for Hermes query patterns

-- Domain-level aggregation (most common Hermes query)
CREATE INDEX IF NOT EXISTS idx_sessions_domain
    ON activity_sessions (domain);

-- Time-range queries (e.g. "last 30 minutes", "today")
CREATE INDEX IF NOT EXISTS idx_sessions_start_time
    ON activity_sessions (start_time DESC);

-- Partial index: only completed sessions that Hermes hasn't seen yet
-- Hermes will use: WHERE end_time IS NOT NULL AND start_time > <last_run_ts>
CREATE INDEX IF NOT EXISTS idx_sessions_completed
    ON activity_sessions (start_time)
    WHERE end_time IS NOT NULL;

-- =============================================================================
--  Verify
-- =============================================================================
SELECT 'activity_sessions table ready.' AS status;
\d activity_sessions
